version: '3.8'

services:
  api:
    build:
      context: ./docker
      dockerfile: Dockerfile.api
    volumes:
      - ./services/api:/var/www
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend
    volumes:
      - ./services/frontend:/app
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
